closes #1
cichan02/airline-service pull request #3
Opened 2023-04-04 12:49 UTC by cichan02

2023-04-05 12:27 UTC, h1alexbel requested changes

2023-04-05 12:27 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/impl/AirlineQueryServiceImpl.java
> +						 .orElseThrow(() -> new ResourceNotExistsException("There's no airline with such id"));
line is too long

2023-04-05 12:27 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/web/controller/AdviceController.java
> +                          .map(globalError -> new ErrorResponseDTO(globalError.getObjectName(), globalError.getDefaultMessage()))
line is too long

2023-04-05 12:27 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/web/dto/groups/onCreate.java
> +public interface onCreate {
please follow Java code conventions

2023-04-05 12:27 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/web/dto/groups/onSearch.java
> +public interface onSearch {
please follow Java code conventions

2023-04-06 11:55 UTC, cichan02 commented on src/main/resources/application.yaml
> +  elasticsearch:
I tried to use, but something got wrong 😢

2023-04-06 14:01 UTC, h1alexbel approved these changes

2023-04-06 14:01 UTC, merged